[0;1;31m‚óè[0m gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
   Active: [0;1;31mfailed[0m (Result: exit-code) since Wed 2017-12-13 06:16:59 UTC; 55s ago
 Main PID: 16479 (code=exited, status=3)

Dec 13 06:16:59 elanvision2018 gunicorn[16479]:     return util.import_app(self.app_uri)
Dec 13 06:16:59 elanvision2018 gunicorn[16479]:   File "/home/kiran/mainwebsite/mainwebsiteenv/local/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
Dec 13 06:16:59 elanvision2018 gunicorn[16479]:     __import__(module)
Dec 13 06:16:59 elanvision2018 gunicorn[16479]: ImportError: No module named elan_vision.wsgi
Dec 13 06:16:59 elanvision2018 gunicorn[16479]: [2017-12-13 06:16:59 +0000] [16488] [INFO] Worker exiting (pid: 16488)
Dec 13 06:16:59 elanvision2018 gunicorn[16479]: [2017-12-13 06:16:59 +0000] [16479] [INFO] Shutting down: Master
Dec 13 06:16:59 elanvision2018 gunicorn[16479]: [2017-12-13 06:16:59 +0000] [16479] [INFO] Reason: Worker failed to boot.
Dec 13 06:16:59 elanvision2018 systemd[1]: [0;1;39mgunicorn.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED[0m
Dec 13 06:16:59 elanvision2018 systemd[1]: [0;1;39mgunicorn.service: Unit entered failed state.[0m
Dec 13 06:16:59 elanvision2018 systemd[1]: [0;1;39mgunicorn.service: Failed with result 'exit-code'.[0m
[0;1;31mWarning:[0m gunicorn.service changed on disk. Run 'systemctl daemon-reload' to reload units.
